account/urls.py
from django.urls import path

from . import views

from django.contrib.auth import views as auth_views

app_name='account'

urlpatterns=[
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
     path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
     path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
     path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
]

moviepost/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name='moviepost'
urlpatterns=[
    path('posted/',
         views.PostedView.as_view(),
         name='posted'),
    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_success'),
    path('usercontents/',
         views.UsercontentsView.as_view(),
         name='usercontents'),
    
     path('usercontents/<int:category>',
         views.UsercontentsmainView.as_view(),
         name = 'usercontents_main'
         ),
     
     path('posted/<int:pk>/delete/',
     views.MovieDeleteView.as_view(),
     name='delete'),
]

urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sikenproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mywebsite.urls')),
    path('',include('account.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view(
        template_name="password_reset.html"),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="password_reset_sent.html"),
         name='password_reset_done'    
         ),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="password_reset_form.html"),
         name='password_reset_confirm'
         ),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_done.html'),
         name='password_reset_complete'),
    path('',include('moviepost.urls')),
    path('',include('comment.urls')),
]

moviepost/models.py
from django.db import models

from account.models import CustomUser


class Category(models.Model):
    title=models.CharField(
        verbose_name='カテゴリ',
        max_length=20
    )
    
    def __str__(self):
        return self.title

class MoviePost(models.Model):
    user=models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )
    
    category=models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
    )
    
    title=models.CharField(
        verbose_name='タイトル',
        max_length=200
    )
    
    gaiyou=models.TextField(
        verbose_name='概要欄',
        max_length=100000
    )
    
    image1=models.ImageField(
        verbose_name='サムネイル',
        upload_to='photos'
    )
    
    movie=models.FileField(
        verbose_name='動画',
        upload_to='photos'       
    )
    
    posted_at=models.DateField(
        verbose_name='投稿日時',
        auto_now_add=True,

    )
    def __str__(self):
        return self.title    

moviepost/forms.py
from django.forms import ModelForm
from .models import MoviePost

class MoviePostForm(ModelForm):
    '''ModelFormのサブクラス
    '''
    class Meta:
        '''ModelFormのインナークラス
        
        Attributes:
          model: モデルのクラス
          fields: フォームで使用するモデルのフィールドを指定
        '''
        model = MoviePost
        fields = ['user','category','title','image1','movie','gaiyou']

moviepost/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
# django.views.genericからTemplateView、ListViewをインポート
from django.views.generic import TemplateView, ListView,DetailView,DeleteView
# django.views.genericからCreateViewをインポート
from django.views.generic import CreateView
# django.urlsからreverse_lazyをインポート
from django.urls import reverse_lazy
# formsモジュールからPhotoPostFormをインポート
from .forms import MoviePostForm
# method_decoratorをインポート
from django.utils.decorators import method_decorator
# login_requiredをインポート
from django.contrib.auth.decorators import login_required
# modelsモジュールからモデルPhotoPostをインポート
from .models import MoviePost


@method_decorator(login_required,name='dispatch')
class PostedView(CreateView):
    form_class=MoviePostForm
    template_name = "post.html"
    success_url = reverse_lazy('moviepost:post_success')
    def form_valid(self,form):
        postdata=form.save(commit=False)
        postdata.user=self.request.user
        postdata.save()
        return super().form_valid(form)
    
class PostSuccessView(TemplateView):
    template_name ='post_success.html'
    
class UsercontentsView(ListView):
    template_name='contents_home.html'
    context_object_name='orderby_records'
    queryset=MoviePost.objects.order_by('-posted_at')
    paginate_by=4
    
class UsercontentsmainView(ListView):
    template_name='contents_main.html'
    context_object_name='orderby_records'
    queryset=MoviePost.objects.order_by('-posted_at')
    paginate_by=4
    
    
class MovieDeleteView(DeleteView):
  model=MoviePost
  template_name='delete.html'
  success_url=reverse_lazy('mywebsite:home')
  def delete(self,request,*args,**kwargs):
    return super().delete(request,*args,**kwargs)

moviepost/templates/contents_home.html
{% extends 'base.html' %}
{% block title %}会員限定コンテンツ-Home{% endblock %}
{% block contents %}
<div id="wrapper">
    <div id="main_youtube">
        <h2>UserContents</h2>

<div id="maincontents">
<ul>{% for record in object_list %}

<br>
<li><a href="{% url 'moviepost:usercontents_main' record.pk %}"><img src="{{ record.image1.url }}" alt="" width="320" height="180">{{record.title}}</a></li>
<br>
{% endfor %}
</ul>    
</div>
</div>
</div>
{% if user.is_authenticated %}
{% else %}
<h3>会員登録した方のみ見られるコンテンツです。</h3>
<p>会員登録は<a href="{% url 'account:signup' %}">こちら</a></p>
{% endif %}
{% endblock %}

moviepost/templates/contents_main.html
{% extends 'base.html' %}
{% block title %}{{record.title}}{% endblock %}
{% block contents %}
{% for record in object_list %}
<br>
<div id="moviecontents">
<h2>{{record.title}}</h2>
<div id="moviemain">
<video controls src="{{ record.movie.url }}" width="932" height="500" id="movie"></video>
<br>
<br>
<h3>サムネイル　:　</h3><br>
<img src="{{ record.image1.url }}" alt="" width="320" height="180">

<!-- {% include "./commentpost.html" %} -->
</div>  
<h4>概要</h4>          
<aside id="sidebar_gaiyou">
{{record.gaiyou}}
</aside>
</div>
{% endfor %}
{% if user.is_authenticated %}
{% else %}
<h3>会員登録した方のみ見られるコンテンツです。</h3>
<p>会員登録は<a href="{% url 'account:signup' %}">こちら</a></p>
{% endif %}
{% endblock %}

moviepost/templates/delete.html
{% extends 'base.html' %}
{% block title %}投稿の削除{% endblock %}
{% block contents %}
<br>
            <form method="POST">
                <br>
                <p>削除してもよろしいですか？</p>
                {% csrf_token %}
                <button type="submit">削除</button>
                <a href="{% url 'mywebsite:home' %}" >キャンセル</a>
{% endblock %}

moviepost/templates/post.html
{% extends 'base.html' %}
{% block  title %}投稿ページ{% endblock %}
{% block contents %}
<div id="postmovie">
<form method="POST"  id="entry"
enctype="multipart/form-data">
{% csrf_token %}
<dl>
    {% for field in form %}
          <dt>
          <!-- <label>タグを生成-->
          {{ field.label_tag }}
          <!-- フィールドの設定値を<input>タグで出力-->
          {{ field }}
        </dt>
    {% endfor %}
    <!-- forループここまで -->
  </dl>


<hr>
<button type="submit" id="submit_button">投稿する</button>
</form>
</div>
{% endblock %}

moviepost/templates/post_success.html
{% extends 'base.html' %}
{% block title %}投稿完了{% endblock %}
{% block contents %}
<h3>
    投稿が完了しました。今一度投稿されているか<a href="{% url 'moviepost:usercontents' %}">投稿ページ</a>に戻って確認してみてください。
</h3>

<a href="{% url 'mywebsite:home' %}">ホームに戻る</a>
{% endblock %}