account/urls.py
from django.urls import path

from . import views

from django.contrib.auth import views as auth_views

app_name='account'

urlpatterns=[
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
     path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
     path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
     path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
]

sikenproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mywebsite.urls')),
    path('',include('account.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view(
        template_name="password_reset.html"),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="password_reset_sent.html"),
         name='password_reset_done'    
         ),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="password_reset_form.html"),
         name='password_reset_confirm'
         ),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_reset_done.html'),
         name='password_reset_complete'),
    path('',include('moviepost.urls')),
    path('',include('comment.urls')),
]

account/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

account/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model=CustomUser
        fields=('username','email','password1','password2')

account/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    '''サインアップページのビュー
    
    '''
    # forms.pyで定義したフォームのクラス
    form_class = CustomUserCreationForm
    # レンダリングするテンプレート
    template_name = "signup.html"
    # サインアップ完了後のリダイレクト先のURLパターン
    success_url = reverse_lazy('account:signup_success')

    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録を行う
        
        parameters:
          form(django.forms.Form):
            form_classに格納されているCustomUserCreationFormオブジェクト
        Return:
          HttpResponseRedirectオブジェクト:
            スーパークラスのform_valid()の戻り値を返すことで、
            success_urlで設定されているURLにリダイレクトさせる
        '''
        # formオブジェクトのフィールドの値をデータベースに保存
        user = form.save()
        self.object = user
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    '''サインアップ成功ページのビュー
    
    '''
    # レンダリングするテンプレート
    template_name = "signup_success.html"

account/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ログイン{% endblock %}
{% block contents %}
{% if form.errors %}
<p style="color: red">ユーザー名とパスワードが一致しません。</p>
{% endif %}
<form method="post">
    {% csrf_token %}
    <label for="Username">
        User name</label>
      <!-- usernameの<input>タグを出力-->
      <!-- name属性の値はLoginViewで定義されているフィールド名username -->
      <input type="text"
             name="username"
             id="id_username"
             maxlength="150"
             autocapitalize="none"
             autocomplete="username"
             class="form-control"
             placeholder="ユーザー名"
             required autofocus>
      <!-- Passwordのラベル(非表示) -->
      <br>
      <label for="Password" class="visually-hidden">
         Password</label>
      <!-- passwordの<input>タグを出力-->
      <!-- name属性の値はLoginViewで定義されているフィールド名password -->
      <input type="password"
             name="password"
             id="id_password"
             autocomplete="current-password"
             class="form-control"
             placeholder="パスワード"
             required autofocus>
      
      <!-- <button>～</button>を書き換えてログインボタンを配置 -->
          <input type="submit" value="ログイン">
      
      <!-- パスワードリセットページのリンクテキスト -->
      <br><br>
      <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか?</a><p>
      <!-- ログイン直後のリダイレクト先(トップページ)のURLパターンを設定 -->
      <input type="hidden"
             name="next"
             value="{% url 'mywebsite:home' %}">
    </form>
    {% endblock %}

account/templates/logout.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}ログアウト{% endblock %}

      {% block contents %}

          <h3>ログアウトしました</h3>
          <!-- トップページのリンクテキスト -->
          <p><a href="{% url 'mywebsite:home' %}">トップページへ</a><p>
      {% endblock %}

account/templates/password_reset.html
{% extends 'base.html' %}
{% block title %}パスワードのリセット{% endblock %}
{% block contents %}
<h3>パスワードのリセットを行いたい場合のみこちらを利用してください</h3>
<p>登録済みのメールアドレスを入力して下さい</p>
<br>
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="メールを受け取る" /><br>
</form>
<br>

<a href="{% url 'mywebsite:home' %}">ホーム画面に戻る</a>
<hr>
{% endblock %}

account/templates/password_reset_done.html
{% extends 'base.html' %}
{% block title %}パスワードのリセット完了{% endblock %}
{% block contents %}
<h2>パスワードのリセットが完了しました。</h2>

<br>
<br>
<a href="{% url 'mywebsite:home' %}">ホーム画面に戻る</a>

{% endblock %}

account/templates/password_reset_form.html
{% extends 'base.html' %}
{% block title %}パスワードのリセット{% endblock %}
{% block contents %}
<h2>パスワードのリセット</h2>
<h4>新しいパスワードを2回入力してください。正しく入力されたかの確認になります。</h4>
<br>
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="パスワードのリセット">
</form>
{% endblock %}

account/templates/password_reset_sent.html
{% extends 'base.html' %}
{% block title %}メールを送信しました{% endblock %}
{% block contents %}
<hr>
<h5>パスワードをリセットするリンクをメールで送信しました。
    手順の通りにお進みください。
</h5>

<br>

<h6>メールが届かない場合には登録済みのメールアドレスとご入力いただいたメールアドレスが異なる場合があります。
    お手数ですがその場合には再度入力をしてください。
</h6>

<a href="{% url 'mywebsite:home' %}">ホーム画面に戻る</a>

{% endblock %}

account/templates/signup.html
{% extends 'base.html' %}
{% block title %}サインアップ{% endblock %}
{% block contents %}
<hr>
<div id="signup">
    <h3>サインアップ</h3>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
            {{ field.help_text }}
            {% endif %}

            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
            {% endfor %}
        </p>
        {% endfor %}
        <input type="submit" value="Sign up">
        <p><a href="{% url 'password_reset' %}">パスワードを忘れたときはこちら</a></p>
    </form>
    <br>
    <p><a href="{% url 'mywebsite:home' %}">ホームに戻る</a></p>
</div>
{% endblock %}

account/templates/signup_success.html
{% extends 'base.html' %}
{% block title %}アカウント作成完了{% endblock %}
{% block contents %}
<h3>登録が完了しました！</h3>
<p><a href="{% url 'account:login' %}">ログインはこちらから</a></p>
{% endblock %}